### ISSUE TITLE
Any plan to release your paper?

### ISSUE THREAD

**Issue by funnyday16** [daooshee/HLA-Face-Website#1]
:)

**Comment by daooshee** [comment]
Thank you for your interest in our work. I plan to release the paper after I upload the code to Github. Maybe next week I can finish cleaning up the code and release the paper.

**Comment by funnyday16** [comment]
> Thank you for your interest in our work. I plan to release the paper after I upload the code to Github. Maybe next week I can finish cleaning up the code and release the paper.

Thanks!

**Comment by daooshee** [comment]
Hi, we have released our [paper](https://arxiv.org/abs/2104.01984) and [code](https://github.com/daooshee/HLA-Face-Code) :)

**Comment by funnyday16** [comment]
> Hi, we have released our [paper](https://arxiv.org/abs/2104.01984) and [code](https://github.com/daooshee/HLA-Face-Code) :)

Nice work~
